minishell:minishell.c
	gcc $^ -o $@
exec:exec.c
	gcc $^ -o $@
wait:wait.c
	gcc $^ -o $@
exit:exit.c
	gcc $^ -o $@
vfork:vfork.c
	gcc $^ -o $@
env:env.c
	gcc $^ -o $@
status:status.c
	gcc $^ -o $@
create:create.c
	gcc $^ -o $@
main:main.c
	gcc $^ -o $@
